# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_1 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_smc_1/zynq_design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_smc_1 || ORIG_REF_NAME==zynq_design_1_axi_smc_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_matrix_multiplier_0_7/zynq_design_1_matrix_multiplier_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_1_matrix_multiplier_0_7 || ORIG_REF_NAME==zynq_design_1_matrix_multiplier_0_7} -quiet] -quiet

# XDC: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.gen/sources_1/bd/zynq_design_1/zynq_design_1_ooc.xdc
