# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1.xci
# IP: The module: 'zynq_design_1_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.gen/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.gen/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1.xci
# IP: The module: 'zynq_design_1_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.gen/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado/ENGG 3050/Custom_Matrix_Multiplier/Block_Design/Block_Design.gen/sources_1/bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_1/zynq_design_1_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
